# Generated by Django 4.2 on 2026-06-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_conatactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conatact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Conatactus',
        ),
    ]
